language: python
python: 2.7

env:
  global:
    - AWS_DEFAULT_REGION=us-east-1
    - AWS_DEFAULT_OUTPUT=text

install:
  - pip install awscli
  - pip install ansible

before_script:
  - aws --version
  - ansible --version

script:
  - ansible-playbook --inventory-file=hosts --syntax-check playbooks/vyos-build-ami.yml
