---
- name: Provision instance
  hosts: local
  connection: local
  gather_facts: True

  tasks:
    - name: Make sure that files/ssh-keys directory exists
      file:
        path: "{{ temp_folder }}"
        state: directory

    - name: Create an SSH key pair
      ec2_key:
        name: "{{ key_pair_name }}"
        region: "{{ ec2_region }}"
        wait: True
      register: key_pair

    - name: Dump key pair
      copy:
        content: "{{ key_pair.key.private_key }}"
        dest: "{{ key_pair_file }}"
        mode: 0600

    - name: Create temporary VPC
      ec2_vpc_net:
        state: present
        region: "{{ ec2_region }}"
        name: "{{ placeholder }}"
        cidr_block: 10.0.0.0/16
        resource_tags:
          Type: vyos-build-ami
          Name: "{{ placeholder }}"
        region: "{{ ec2_region }}"
      register: build_vpc

    - name: Create VPC subnet
      ec2_vpc_subnet:
        state: present
        region: "{{ ec2_region }}"
        vpc_id: "{{ build_vpc.vpc.id }}"
        cidr: 10.0.0.0/16
        resource_tags:
          Name: build_subnet
      register: build_subnet

    - name: Create a gateway for the temporary VPC
      ec2_vpc_igw:
        state: present
        region: "{{ ec2_region }}"
        vpc_id: "{{ build_vpc.vpc.id }}"
      register: igw

    - name: Setup VPC routes
      ec2_vpc_route_table:
        state: present
        vpc_id: "{{ build_vpc.vpc.id }}"
        region: "{{ ec2_region }}"
        subnets:
          - "{{ build_subnet.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw.gateway_id }}"
      register: vpc_route_table

    - name: Create temporary security group
      ec2_group:
        name: vyos_build_instance_access
        description: This security group was generated by ansible playbook vyos_build_ami.yml
        region: "{{ ec2_region }}"
        vpc_id: "{{ build_vpc.vpc.id }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
      register: temp_security_group

    # Look up the AMI id to use based on a search
    - name: Look up Debian Jessie AMI
      ec2_ami_facts:
        owners: 379101102735
        filters:
          name: "debian-jessie-amd64-hvm-*"
          architecture: "x86_64"
          hypervisor: "xen"
          "root-device-type": "ebs"
          state: available
      register: debian_ami

    # ---- Launch EC2 instance ----
    - name: Launch an EC2 instance
      ec2:
        key_name: "{{ key_pair_name }}"
        assign_public_ip: True
        image: "{{ debian_ami.images[0].image_id }}"
        instance_type: "{{ instance_type }}"
        region: "{{ ec2_region }}"
        vpc_subnet_id: "{{ build_subnet.subnet.id }}"
        wait: yes
        instance_tags:
          Name: "{{ placeholder }}"
          Type: "VyOS"
        volumes:
          - device_name: /dev/sdf
            volume_type: gp2
            volume_size: "{{ volume_size }}"
            delete_on_termination: True
      register: ec2_instance

    - name: Add instance's public DNS name to ansible host group ec2
      add_host:
        name: "{{ ec2_instance.instances[0].public_ip }}"
        groups: ec2

    - debug: msg="{{ ec2_instance.instances[0].public_ip }}"

    - name: Wait for instance's SSH port to open
      wait_for:
        host: "{{ ec2_instance.instances[0].public_ip }}"
        port: 22
        delay: 10
        timeout: 120
        state: started
